recipe_version: '1'
model: nvidia/Qwen3.6-27B-NVFP4
builder: isc30
container: eugr/spark-vllm:latest
mods:
  - mods/fix-qwen3.6-chat-template
defaults:
  served_model_name: qwen3.6-27b
  port: 8001
  host: 0.0.0.0
  tensor_parallel: 1
  gpu_memory_utilization: 0.8 # SINGLE-MODEL
  kv_cache_memory: 20042098000 # MULTI-MODEL # 1.0x=9971193034
  max_model_len: 262144
  max_num_batched_tokens: 32768
  max_num_seqs: 24
command: |
  vllm serve nvidia/Qwen3.6-27B-NVFP4 \
    --host {host} \
    --port {port} \
    --served-model-name {served_model_name} \
    --tensor-parallel-size {tensor_parallel} \
    --optimization-level 3 \
    --trust-remote-code \
    --kv-cache-dtype fp8 \
    --load-format safetensors \
    --attention-backend flashinfer \
    --gpu-memory-utilization {gpu_memory_utilization} \
    --kv-cache-memory {kv_cache_memory} \
    --max-model-len {max_model_len} \
    --max-num-batched-tokens {max_num_batched_tokens} \
    --max-num-seqs {max_num_seqs} \
    --enable-chunked-prefill \
    --async-scheduling \
    --enable-prefix-caching \
    --reasoning-parser qwen3 \
    --enable-auto-tool-choice \
    --tool-call-parser qwen3_xml \
    --default-chat-template-kwargs '{"preserve_thinking":true}' \
    --generation-config auto \
    --override-generation-config '{"temperature": 0.6, "top_p": 0.95, "top_k": 20, "min_p": 0.0, "presence_penalty":0.0, "repetition_penalty":1.1}' \
    --chat-template fixed_chat_template.jinja \
    --quantization modelopt \
    --speculative-config '{"method":"mtp","num_speculative_tokens":3,"attention_backend":"triton_attn"}' \
env:
  # defaults for gb10
  CUTE_DSL_ARCH: sm_121a
  TORCH_CUDA_ARCH_LIST: 12.1a
  ENABLE_NVFP4_SM100: 0
  # vllm
  VLLM_HTTP_TIMEOUT_KEEP_ALIVE: '600'
  # cache
  PYTORCH_CUDA_ALLOC_CONF: 'expandable_segments:True'
  VLLM_CACHE_ROOT: /cache/huggingface/vllm-cache
  TRITON_CACHE_DIR: /cache/huggingface/triton-cache
  TORCHINDUCTOR_CACHE_DIR: /cache/huggingface/torchinductor-cache
  TORCHINDUCTOR_FX_GRAPH_CACHE: '1'
  # build
  MAX_JOBS: '4'
  NVCC_THREADS: '2'
  FLASHINFER_NVCC_THREADS: '2'
