recipe_version: '1'
model: huihui-ai/Huihui-Qwen3.5-0.8B-abliterated
builder: isc30
container: ghcr.io/spark-arena/dgx-vllm-eugr-nightly:latest
mods:
  - mods/fix-qwen3.5-chat-template
defaults:
  served_model_name: qwen3.5-0.8b
  port: 8003
  host: 0.0.0.0
  tensor_parallel: 1
  gpu_memory_utilization: 0.1 # KEEP LINE ONLY IF SINGLE-MODEL
  kv_cache_memory: 20042098000 # KEEP LINE ONLY IF MULTI-MODEL # 1.0x=9971193034
  max_model_len: 65536
  max_num_batched_tokens: 32768
  max_num_seqs: 24
command: |
  vllm serve huihui-ai/Huihui-Qwen3.5-0.8B-abliterated \
    --host {host} \
    --port {port} \
    --served-model-name {served_model_name} \
    --tensor-parallel-size {tensor_parallel} \
    --optimization-level 3 \
    --trust-remote-code \
    --kv-cache-dtype fp8 \
    --load-format safetensors \
    --gpu-memory-utilization {gpu_memory_utilization} \
    --kv-cache-memory {kv_cache_memory} \
    --max-model-len {max_model_len} \
    --max-num-batched-tokens {max_num_batched_tokens} \
    --max-num-seqs {max_num_seqs} \
    --enable-chunked-prefill \
    --async-scheduling \
    --enable-prefix-caching \
    --reasoning-parser qwen3 \
    --enable-auto-tool-choice \
    --tool-call-parser qwen3_xml \
    --default-chat-template-kwargs '{"preserve_thinking":false}' \
    --generation-config auto \
    --override-generation-config '{"temperature":1.0,"top_p":1.00,"top_k":20,"min_p":0.0,"presence_penalty":2.0,"repetition_penalty":1.0}' \
    --chat-template unsloth.jinja \
    --quantization modelopt \
    --speculative-config '{"method":"mtp","num_speculative_tokens":4,"attention_backend":"triton_attn"}' \
env:
  # defaults for gb10
  CUTE_DSL_ARCH: sm_121a
  TORCH_CUDA_ARCH_LIST: 12.1a
  ENABLE_NVFP4_SM100: '0'
  PYTORCH_CUDA_ALLOC_CONF: 'expandable_segments:True'
  # vllm
  VLLM_MARLIN_USE_ATOMIC_ADD: '1'
  VLLM_HTTP_TIMEOUT_KEEP_ALIVE: '600'
  CUDA_MODULE_LOADING: LAZY
  # cache
  VLLM_CACHE_ROOT: /cache/huggingface/vllm-cache
  TRITON_CACHE_DIR: /cache/huggingface/triton-cache
  TORCHINDUCTOR_CACHE_DIR: /cache/huggingface/torchinductor-cache
  TORCHINDUCTOR_FX_GRAPH_CACHE: '1'
  # build
  MAX_JOBS: '4'
  NVCC_THREADS: '2'
  FLASHINFER_NVCC_THREADS: '2'
